[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hume[microphone]>=0.11.6",
    "python-dotenv>=1.1.1",
    "openai>=1.108.2"
]
